//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSFD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logins
    {
        public Logins(string name, string password)
        {
            this.name = name;
            this.password = Cryptography.Encrypt(password);
        }
        public int id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
    }
}
