//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSFD
{
    using System;
    using System.Collections.Generic;
    
    public partial class movieAliases
    {
        public movieAliases()
        {
            
        }

        public movieAliases(int movieID,string alias)
        {
            this.movieID = movieID;
            this.alias = alias;
        }
        public int movieID { get; set; }
        public string alias { get; set; }
    
        public virtual Movie Movie { get; set; }
    }
}
