//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSFD
{
    using System;
    using System.Collections.Generic;
    
    public partial class personalEdit
    {
        public personalEdit()
        {
            
        }
        public personalEdit(int accountID,int movieID,int rating, string datetime)
        {
            this.accountID = accountID;
            this.movieID = movieID;
            this.rating = rating;
            this.datetime = datetime;
        }
        public int accountID { get; set; }
        public int movieID { get; set; }
        public Nullable<int> rating { get; set; }
        public string datetime { get; set; }
        public virtual account account { get; set; }
    }
}
